name: jigsaw_puzzle_example
description: Jigsaw Puzzle lib example.
version: 0.1.0
homepage: https://github.com/edunuzzi/flutter_jigsaw_puzzle
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jigsaw_puzzle:
    path: ../
    
flutter:
  uses-material-design: true
  assets:
    - assets/