name: flutter_jigsaw_puzzle
description: A simple Jigsaw Puzzle lib built with Flutter that supports custom grids of varying sizes.
version: 0.1.0
homepage: https://github.com/o-compilador/flutter_jigsaw_puzzle

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^3.0.5
  carousel_slider: ^4.0.0